outf: shrec16/meshnet/default
timelimit: 9999999
timescale: 1.3
logger:
  name: ''
  overwrite: 1
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      from_basic_blocks: datasets/shrec_meshnet/train.yaml
    dataloader:
      from_basic_blocks: dataloaders/shrec_meshnet_trans/default.yaml
  val:
    dataset:
      from_basic_blocks: datasets/shrec_meshnet/test.yaml
    dataloader:
      from_basic_blocks: dataloaders/shrec_meshnet_trans/default.yaml
  test: null
model:
  from_basic_blocks: models/shrec_meshnet.yaml
optim:
  from_basic_blocks: optimizer/adam.yaml
  params:
    lr: 0.0002
  scheduler: 
    name: None
train:
  from_basic_blocks: trainer/classification.yaml
  max_epoch: 300
  train_freq: 5
