based_on:
  - train000.yaml
outf: 'finetune/train_2_007'
data:
  train:
    dataset:
      params:
        fold_group: 7
  val:
    dataset:
      params:
        fold_group: 7
  test:
    dataset:
      params:
        fold_group: 7
