based_on:
  - train000.yaml
outf: 'finetune/train_2_006'
data:
  train:
    dataset:
      params:
        fold_group: 6
  val:
    dataset:
      params:
        fold_group: 6
  test:
    dataset:
      params:
        fold_group: 6
