name: 'pnvae_shapenet'
log_name: 'pnvae_shapenet'
outf: 'pnvae_shapenet/default'
seed: 0
data:
  train:
    dataset:
      center: 1
      noise_da: 1
      noise_level: 0.02
      rot_da: 1
      scale: 1
      split: 'train'
      type: 'ShapeNetPointCloud'
    dataloader:
      collate_fn: pnvae_shapenet
      batch_size: 50
      num_workers: 5
      drop_last: 1
  test:
    dataset:
      center: 1
      noise_da: 0
      noise_level: 0.00
      rot_da: 0
      scale: 1
      split: 'val'
      type: 'ShapeNetPointCloud'
    dataloader:
      collate_fn: pnvae_shapenet
      batch_size: 50
      num_workers: 5
      drop_last: 0
model:
  name: PointNetVAE
  params:
    is_vae: false
    bneck_size: 512
optim:
  name: 'Adam'
  params:
    lr: 5.0e-4
    betas: [0.9,0.999]
  scheduler:
    name: StepLR
    params:
      step_size: 20
      gamma: 0.5
train:
  load: 0
  trainer: PointNetVAETrainer
  max_epoch: 1000
  load_epoch: 20
  loss_params:
    is_vae: false
    kl_weight: 0.01
  scheduler_step: 1
  val_freq: 1
  