outf: shapenetpart/meshnet2/ssl_mae_test/train
timelimit: -1
timescale: 1.3
logger:
  name: ''
  overwrite: 1
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      from_basic_blocks: datasets/shapenetpart/meshnet2/ssl_mae_test/train/train.yaml
    dataloader:
      from_basic_blocks: dataloaders/shapenetpart/meshnet2/ssl_mae_test/train/train.yaml
  val: null
    # dataset:
    #   from_basic_blocks: datasets/shapenetpart/meshnet2/ssl_mae_test/train/val.yaml
    # dataloader:
    #   from_basic_blocks: dataloaders/shapenetpart/meshnet2/ssl_mae_test/train/val.yaml
  test:
    dataset:
      from_basic_blocks: datasets/shapenetpart/meshnet2/ssl_mae_test/train/test.yaml
    dataloader:
      from_basic_blocks: dataloaders/shapenetpart/meshnet2/ssl_mae_test/train/test.yaml
model:
  from_basic_blocks: models/shapenetpart/meshnet2/ssl_mae_test/train.yaml
optim:
  from_basic_blocks: optimizers/modelnet40/meshnet2/ssl_rec_att.yaml
  params:
    lr: 0.0002
  scheduler:
    name: fakemade
  #   params:
  #     milestones: [30, 60]
  #     gamma: 0.1
train:
  from_basic_blocks: trainers/shapenetpart/meshnet2/ssl_mae_test/train.yaml
  max_epoch: 30
  train_freq: 5
  # debug: false
