based_on:
  - train000.yaml
outf: 'finetune/train_2_004'
data:
  train:
    dataset:
      params:
        fold_group: 4
  val:
    dataset:
      params:
        fold_group: 4
  test:
    dataset:
      params:
        fold_group: 4
