based_on:
  - train000.yaml
outf: 'finetune/train_2_009'
data:
  train:
    dataset:
      params:
        fold_group: 9
  val:
    dataset:
      params:
        fold_group: 9
  test:
    dataset:
      params:
        fold_group: 9
