based_on:
  - train000.yaml
outf: 'finetune/train_2_001'
data:
  train:
    dataset:
      params:
        fold_group: 1
  val:
    dataset:
      params:
        fold_group: 1
  test:
    dataset:
      params:
        fold_group: 1
