outf: modelnet40/meshnet2/ssl_mae/0_9/
timelimit: 14400
timescale: 1.3
logger:
  name: ''
  overwrite: 1
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      from_basic_blocks: datasets/modelnet40/meshnet2/ssl_rec_att/train.yaml
    dataloader:
      from_basic_blocks: dataloaders/modelnet40/meshnet2/ssl_rec_att/train.yaml
  val:
    dataset:
      from_basic_blocks: datasets/modelnet40/meshnet2/ssl_rec_att/val.yaml
    dataloader:
      from_basic_blocks: dataloaders/modelnet40/meshnet2/ssl_rec_att/val.yaml
  test: null
model:
  from_basic_blocks: models/modelnet40/meshnet2/ssl_mae/0_9.yaml
optim:
  from_basic_blocks: optimizers/modelnet40/meshnet2/ssl_rec_att.yaml
  params:
    lr: 0.0002
  scheduler:
    name: MultiStepLR
    params:
      milestones: [30, 60]
      gamma: 0.1
train:
  from_basic_blocks: trainers/modelnet40/meshnet2/ssl_rec_att.yaml
  max_epoch: 300
  train_freq: 5
