based_on:
  - train000.yaml
outf: 'finetune/train_0_005'
data:
  train:
    dataset:
      params:
        fold_group: 5
  val:
    dataset:
      params:
        fold_group: 5
  test:
    dataset:
      params:
        fold_group: 5
