based_on:
  - train000.yaml
outf: 'finetune/train_0_003'
data:
  train:
    dataset:
      params:
        fold_group: 3
  val:
    dataset:
      params:
        fold_group: 3
  test:
    dataset:
      params:
        fold_group: 3
