outf: shapenetpart/meshnet2/ssl_mae/0_3/
timelimit: -1
timescale: 1.3
logger:
  name: ''
  overwrite: 1
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      params:
        placeholder: null
      # from_basic_blocks: datasets/shapenetpart/meshnet2/ssl_mae/train.yaml
    dataloader:
      # from_basic_blocks: dataloaders/modelnet40/meshnet2/ssl_rec_att/train.yaml
  val: null
  test: null
model:
  # from_basic_blocks: models/modelnet40/meshnet2/ssl_mae/0_3.yaml
optim:
  # from_basic_blocks: optimizers/modelnet40/meshnet2/ssl_rec_att.yaml
  params:
    lr: 0.0002
  scheduler:
    name: MultiStepLR
    params:
      milestones: [30, 60]
      gamma: 0.1
train:
  # from_basic_blocks: trainers/modelnet40/meshnet2/ssl_rec_att.yaml
  max_epoch: 300
  train_freq: 5
  save_at_train: true
  # debug: true