version: '3.8'
services:
  brain:
    build:
      context: .
    container_name: brain
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    image: dadadadockerer/brain:0.1
    ports:
      - 5566:5566
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ../src/:/workspace/
      - ../runtime/:/runtime/
