based_on:
  - debug.yaml
outf: multi-view/train
data:
  train:
    dataset:
      params:
        debug: false
    dataloader:
      num_workers: 10
  val:
    dataset:
      params:
        debug: false
train:
  max_epoch: 200
  train_freq: 50
