based_on:
  - train.yaml
logger:
  name: 'test'
data:
  train:
    dataset:
      name: ModelNetDataset
      lib: ModelNetDataset
      params:
        center: 1
        rot_da: 0
        noise_da: 0
        noise_level: 0.00
        root: /dataset/modelnet/modelnet40_ply_hdf5_2048/
        scale: 1
        split: 'train'
    dataloader:
      collate_fn: pointnet_modelnet_cdt
      batch_size: 32
      num_workers: 3
      drop_last: 1
  val:
    dataset:
      name: ModelNetDataset
      lib: ModelNetDataset
      params:
        center: 1
        rot_da: 0
        noise_da: 0
        noise_level: 0.00
        root: /dataset/modelnet/modelnet40_ply_hdf5_2048/
        scale: 1
        split: val
    dataloader:
      collate_fn: pointnet_modelnet_cdt
      batch_size: 32
      num_workers: 3
      drop_last: 0
  test: null
model:
  name: pointnet_conditional
  lib: FCNet
  params:
    have_da_embed: true
    have_fc: true
    da_ratio: 0.5
test:
  name: PCNEncoderTester
  lib: PCNEncoderTester
  load_epoch: 157
