outf: jigsaw/moco/pointnet/structure/debug
# 4 hour =  4 * 60 * 60 = 14400
timelimit: 14400
timescale: 1.3
logger:
  name: ''
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      name: modelnet_jigsaw
      lib: JigsawMoCo
      params:
        center: true
        debug: true
        noise_da: false
        noise_level: 0.02
        root: /dataset/modelnet/modelnet40_ply_hdf5_2048/
        rot_da: false
        scale: true
        split: train
    dataloader:
      collate_fn: occo_moco
      batch_size: 32
      num_workers: 0
      drop_last: 1
  val:
    dataset:
      name: modelnet_jigsaw
      lib: JigsawMoCo
      params:
        center: true
        debug: true
        noise_da: false
        noise_level: 0.02
        root: /dataset/modelnet/modelnet40_ply_hdf5_2048/
        rot_da: false
        scale: true
        split: val
    dataloader:
      collate_fn: occo_moco
      batch_size: 32
      num_workers: 10
      drop_last: 0
  test: null
model:
  name: MoCo
  lib: MoCo
  params:
    base_encoder: 
      name: pointnet_jigsaw_moco
      lib: SimpleNet
    tran0: false
    tran1: false
optim:
  name: 'SGD'
  params:
    lr: 3.0e-2
    momentum: 0.9
    weight_decay: 1.0e-4
  scheduler:
    name: my_own_scheduler
    params:
      step_size: 20
      gamma: 0.5
train:
  # mode 0: train from scratch
  # mode 1: train from pre-train
  # mode 2: train from restore
  # mode 3: search and load the latest ckpt
  mode: 3
  params_0: null
  params_1:
    ckpt_name: spoc.pth
  params_2:
    load_epoch: 15
  trainer: MoCoTrainer
  max_epoch: 3
  loss_params:
    placeholder: 0
  scheduler_step: 1
  test_freq: 1
  train_freq: 1
  val_freq: 1
