lib: Network
name: meshnet2_attention
params:
  num_faces: 500
  num_cls: 30
  cfg: 
    num_kernel: 64
    ConvSurface:
      num_samples_per_neighbor: 4
      rs_mode: 'Weighted'
      num_kernel: 64
    MeshBlock:
      blocks: [3, 4, 4]
  pool_rate: 2
  use_neighbor: true
  op_method: sum
  gather_range: local
  gather_method: softmax
