name: 'test_debug'
outf: 'debugpy'
seed: 0
data:
  train:
    dataset:
      root: '/dataset'
      type: 'ModelNetDataset'
      rot_da: 1
      noise_da: 1
      noise_level: 0.02
      split: 'train'
      center: 1
      scale: 1
    dataloader:
      collate_fn: pointnet_modelnet
      batch_size: 6
      num_workers: 0
      drop_last: 1
  test:
    dataset:
      root: '/dataset'
      type: 'ModelNetDataset'
      rot_da: 0
      noise_da: 0
      noise_level: 0.00
      center: 1
      scale: 1
      split: 'test'
    dataloader:
      collate_fn: pointnet_modelnet
      batch_size: 6
      num_workers: 0
      drop_last: 0
model:
  name: PointNetCls
  params: 
    k: 40
    feature_transform: false
optim:
  name: 'Adam'
  params:
    lr: 1.0e-3
    betas: [0.9,0.999]
  scheduler:
    name: StepLR
    params:
      step_size: 20
      gamma: 0.5
train:
  load: 1
  trainer: ModelNetTrainer
  max_epoch: 10
  load_epoch: 4
  loss_params:
    label_smoothing: true
  scheduler_step: 1
  val_freq: 1
test:
  
