name: 'pnvae_shapenet'
outf: 'pnvae_shapenet'
seed: 0
data:
  train:
    dataset:
      type: 'ShapeNetPointCloud'
      noise_da: 1
      noise_level: 0.02
      split: 'train'
      center: 1
      scale: 1
    dataloader:
      collate_fn: pnvae_shapenet
      batch_size: 32
      num_workers: 5
      drop_last: 1
  test:
    dataset:
      type: 'ShapeNetPointCloud'
      noise_da: 0
      noise_level: 0.00
      center: 1
      scale: 1
      split: 'val'
    dataloader:
      collate_fn: pnvae_shapenet
      batch_size: 32
      num_workers: 5
      drop_last: 0
model:
  name: PointNetVAE
  params:
    is_vae: true
optim:
  name: 'Adam'
  params:
    lr: 1.0e-3
    betas: [0.9,0.999]
  scheduler:
    name: StepLR
    params:
      step_size: 20
      gamma: 0.5
train:
  load: 1
  trainer: PointNetVAETrainer
  max_epoch: 250
  load_epoch: 20
  loss_params:
    is_vae: true
    kl_weight: 0.01
  scheduler_step: 1
  val_freq: 1
  