name: 'Adam'
params:
  lr: 1.0e-4
  betas: [0.9,0.999]
  eps: 1.0e-8
  # the author mentioned set weight decay to 0 is very 
  # important for completion task
  weight_decay: 0.0
scheduler:
  name: StepLR
  params:
    # step_size: 20
    gamma: 0.5
