outf: occo/pretrain/moco/
timelimit: 14400
timescale: 1.3
logger:
  name: ''
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      name: occo_modelnet_moco
      lib: DatasetMoCo
      params:
        root: /dataset/modelnet/occo/
        split: train
    dataloader:
      collate_fn: occo_moco
      batch_size: 32
      num_workers: 3
      drop_last: 1
  val:
    dataset:
      name: occo_modelnet_moco
      lib: DatasetMoCo
      params:
        root: /dataset/modelnet/occo/
        split: val
    dataloader:
      collate_fn: occo_moco
      batch_size: 32
      num_workers: 3
      drop_last: 1
  test: null
model:
  name: MoCo
  params:
    base_encoder: PCNEncoder
    global_feat: true
optim:
  name: 'SGD'
  params:
    lr: 3.0e-2
    momentum: 0.9
    weight_decay: 1.0e-4
  scheduler:
    name: my_own_scheduler
    params:
      step_size: 20
      gamma: 0.5
train:
  # mode 0: train from scratch
  # mode 1: train from pre-train
  # mode 2: train from restore
  # mode 3: search and load the latest ckpt
  mode: 2
  params_0: null
  params_1:
    ckpt_name: spoc.pth
  params_2:
    load_epoch: 1
  trainer: MoCoTrainer
  max_epoch: 200
  loss_params:
    placeholder: 0
  scheduler_step: 1
  test_freq: 1
  train_freq: 50
  val_freq: 1
