outf: occo/pretrain/p/
# 4 hour =  4 * 60 * 60 = 14400
timelimit: 14400
timescale: 1.3
logger:
  name: ''
manager:
  ckpt_prefix: ''
seed: 0
data:
  train:
    dataset:
      name: OcCoModelNetDataset
      lib: OcCoModelNetDataset
      params:
        root: /dataset/modelnet/occo/
        split: train
    dataloader:
      collate_fn: occo_modelnet
      batch_size: 32
      num_workers: 3
      drop_last: 1
  val:
    dataset:
      name: OcCoModelNetDataset
      lib: OcCoModelNetDataset
      params:
        root: /dataset/modelnet/occo/
        split: val
    dataloader:
      collate_fn: occo_modelnet
      batch_size: 32
      num_workers: 3
      drop_last: 0
  test: null
model:
  name: pcn
  params:
    k: 40
    feature_transform: false
optim:
  name: 'Adam'
  params:
    lr: 1.0e-4
    betas: [0.9,0.999]
    eps: 1.0e-8
    # the author mentioned set weight decay to 0 is very 
    # important for completion task
    weight_decay: 0.0
  scheduler:
    name: StepLR
    params:
      step_size: 20
      gamma: 0.5
train:
  # mode 0: train from scratch
  # mode 1: train from pre-train
  # mode 2: train from restore
  # mode 3: search and load the latest ckpt
  mode: 3
  params_0: null
  params_1:
    ckpt_name: spoc.pth
  params_2:
    load_epoch: 15
  trainer: OcCoTrainer
  max_epoch: 50
  loss_params:
    placeholder: 0
  scheduler_step: 1
  test_freq: 1
  train_freq: 50
  val_freq: 1
