outf: supervised_training_pos_neg/exps/train
timelimit: -1
timescale: 1.3
logger:
  name: ""
  overwrite: 1
manager:
  ckpt_prefix: ""
seed: 0
data:
  train:
    dataset:
      params:
        debug: false
        debug_load_num: 16
        data_root: /workspace/data/merged/
        meta_file: meta_pos_neg.json
        processed_root: /workspace/data/merged/processed/
        stage: train
    dataloader:
      collate_fn: __collate__
      batch_size: 16
      num_workers: 4
      drop_last: 0
      shuffle: 1
  val:
    dataset:
      params:
        debug: false
        debug_load_num: 16
        data_root: /workspace/data/merged/
        meta_file: meta_pos_neg.json
        processed_root: /workspace/data/merged/processed/
        stage: val
    dataloader:
      collate_fn: __collate__
      batch_size: 16
      num_workers: 4
      drop_last: 0
      shuffle: 0
  test:
    dataset:
      params:
        debug: false
        debug_load_num: 16
        data_root: /workspace/data/merged/
        meta_file: meta_pos_neg.json
        processed_root: /workspace/data/merged/processed/
        stage: test
    dataloader:
      collate_fn: __collate__
      batch_size: 16
      num_workers: 4
      drop_last: 0
      shuffle: 0
model:
  # from_basic_blocks: models/modelnet40/meshnet2/ssl_mae/0_3.yaml
  lib: Network
  name: null
  params:
    en_config:
      num_faces: 8192
      num_cls: 2
      cfg:
        num_kernel: 64
        ConvSurface:
          num_samples_per_neighbor: 4
          rs_mode: "Weighted"
          num_kernel: 64
        MeshBlock:
          blocks: [3, 4, 4]
      pool_rate: 4
      mask_percentage: 0.3
    de_config:
      bneck_size: 1024
optim:
  # from_basic_blocks: optimizers/modelnet40/meshnet2/ssl_rec_att.yaml
  name: "Adam"
  params:
    lr: 1.0e-4
    betas: [0.9, 0.999]
    eps: 1.0e-8
    # the author mentioned set weight decay to 0 is very
    # important for completion task
    weight_decay: 0.0
  # scheduler:
  #   name: StepLR
  #   params:
  #     # step_size: 20
  #     gamma: 0.5
  #   params:
  #     lr: 0.0002
  scheduler:
    name: MultiStepLR
    params:
      milestones: [30, 60]
      gamma: 0.5
train:
  # from_basic_blocks: trainers/modelnet40/meshnet2/ssl_rec_att.yaml
  max_epoch: 200000
  train_freq: 5
  save_at_train: true
  # debug: true
